acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('changepw/', views.changepw, name="changepw"),
    path('delete/', views.delete, name="delete")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('tts/', include("tts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    content = models.TextField(blank=True)
    point = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y")

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"

acc/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User
from django.contrib import messages
# Create your views here.

def delete(request):
    u = request.user
    cp = request.POST.get("cpass")
    if check_password(cp, u.password):
        u.pic.delete()
        u.delete()
        return redirect("acc:index")
    else:
        pass # 20 일차
        return redirect("acc:profile")

def changepw(request):
    u = request.user
    cp = request.POST.get("cpass")
    if check_password( cp, u.password ):
        np = request.POST.get("npass")
        u.set_password(np)
        u.save()
        return redirect("acc:login")
    else:
        pass # 8일차
    return redirect("acc:update")



def update(request):
    if request.method == "POST":
        u = request.user
        ue = request.POST.get("umail")
        uc = request.POST.get("ucon")
        up = request.FILES.get("upic")
        u.email , u.content = ue, uc
        if up:
            u.pic.delete()
            u.pic = up
        u.save()
        return redirect("acc:profile")
    return render(request, "acc/update.html")

def profile(request):
    return render(request, "acc/profile.html")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("con")
        upic = request.FILES.get("pic")
        try:
            User.objects.create_user(username=un, password=up, content=uc, pic=upic)
            return redirect("acc:login")
        except:
            pass # 8일차 메세지
    return render(request, "acc/signup.html")

def logout_user(request):
    logout(request)
    return redirect("acc:index")

def login_user(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u:
            login(request, u)
            messages.success(request, f"{u}! WELCOME!")
            return redirect("acc:index")   
        else:
            messages.info(request, "계정정보가 일치하지않습니다.")
    return render(request, "acc/login.html")



def index(request):
    return render(request, "acc/index.html")

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>MY FIRST DJANGO PROJECT</b></h1> 
    <h4><b>{{ user }}</b> WELCOME 🎈</h4>
{% endblock %}

{% block noauth %}
    <h1><b>MY FIRST DJANGO PROJECT</b></h1> 
    <h4><b>LOGIN FIRST ! 🎈</h4>
{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block noauth %}
    <h1><b>LOGIN PAGE</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mt-5">
            <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME">
            <input type="password" name="upass" class="form-control mt-4 mb-4" placeholder="INPUT PASSWORD">
            
            <div class="text-end">
                <button class="btn btn-dark">로그인</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>프로필</b></h1>

    <div class="row">
        <div class="col-sm-8">
            <div class="mb-3 mt-5">
                <label class="form-label">USERNAME</label>
                <input type="text" value="{{ user }}" disabled class="form-control" style="font-weight: bold;">
            </div>
            <div class="mb-3">
                <label class="form-label">POINT</label>
                <input type="text" value="{{user.point}} P" style="font-weight: bold;" disabled class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">EMAIL</label>
                <input type="text" value="{{ user.email }}" style="font-weight: bold;" disabled class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{ user.content }}</textarea>
            </div>
        </div>
        <div class="col-sm-4" style="margin: auto;">
            <div class="text-center">
                <img src="{{ user.getpic }}" width="80%">
               
                <a class="btn btn-dark mt-5 btn-lg" href="{% url 'acc:update' %}" style="width: 80%;">프로필수정</a>
                <button type="button" class="btn btn-danger mt-3 btn-lg" style="width: 80%;" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    계정삭제
                </button>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">계정삭제 알림창</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:delete' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <input name="cpass" class="form-control" type="password" placeholder="INPUT CURRENT PASSWORD">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                        <button class="btn btn-danger">삭제</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block noauth %}
    <h1><b>회원가입</b></h1>
    <form method="post" enctype="multipart/form-data" name="registForm">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" name="uname" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">PASSWORD</label>
            <input type="password" name="upass" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">PASSWORD CHECK</label>
            <input type="password" name="ckpass" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" name="con"></textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">USERPIC</label>
            <input type="file" name="pic" class="form-control">
        </div>
        <div class="mt-4 text-end">
            <button class="btn btn-dark" type="button" onclick="check()" style="font-weight: bold;">회원가입</button> 
        </div>
    </form> 

    <script>
        function check(){
            r = document.registForm;
            if(!r.uname.value){
                alert("username 을 입력해주세요 !!");
            }else if(!r.upass.value){
                alert("password 를 입력해주세요 !!");
            }else if(r.upass.value != r.ckpass.value){
                alert("패스워드가 일치하지 않습니다!");
            }else{
                r.submit();
            }
        }
    </script>

{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>프로필수정</b></h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" value="{{user}}" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">EMAIL</label>
            <input type="text" name="umail" value="{{user.email}}" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" name="ucon">{{ user.content }}</textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">USERPIC</label>
            <input type="file" name="upic" class="form-control">
        </div>
        <div class="text-end">
            <a href="{% url 'acc:profile' %}" class="btn btn-dark btn-lg">취소</a>
            <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                패스워드변경
            </button>
            <button class="btn btn-dark btn-lg">변경</button>
        </div>
    </form>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>패스워드 변경창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:changepw' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <input type="password" name="cpass" class="form-control" placeholder="INPUT CURRENT PASSWORD">
                        <input type="password" name="npass" class="form-control mt-3" placeholder="INPUT NEW PASSWORD">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">변경</button>
                    </div>
                </form>
                
            </div>
        </div>
    </div>




{% endblock %}