acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('changepw/', views.changepw, name="changepw"),
    path('delete/', views.delete, name="delete")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>' , views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('tts/', include("tts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trans/urls.py
from django.urls import path
from . import views

app_name = "trans"
urlpatterns = [
    path('index/', views.index, name="index")
]

tts/urls.py
from django.urls import path
from . import views

app_name = "tts"
urlpatterns = [
    path('index/', views.index, name="index")
]

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MY FIRST DJANGO</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>
    <body>

        {% if user.is_authenticated %}
            <!-- 인증된 사용자라면 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black; font-weight: bold; font-size: 20px;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">BOARD</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'trans:index' %}">TRANS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'tts:index' %}">TTS</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Disabled</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>


        {% else %}
            <!-- 익명의 사용자라면 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black; font-weight: bold; font-size: 20px;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

        {% endif %}
        
        {% for i in messages %}
            <div class="alert {{i.tags}} alert-dismissible fade show text-center" role="alert">
                {{i.message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}            

        <style>
            .alert{
                font-size:15px;
                font-weight: bold;
                color: white;
            }
            .success{
                background-color: blue;
            }
            .warning{
                background-color: yellow;
            }
            .info{
                background-color: gray;
            }
            .error{
                background-color: red;
            }
        </style>


        <div class="container mt-5 mb-5">
            {% if user.is_authenticated %}
                {% block con %}
                    <h1 class="text-center"><b>이미 인증된 사용자입니다!</b></h1>
                    <div class="text-center mt-5">
                        <a href="{% url 'board:index' %}" class="btn btn-dark">게시판</a>
                        <a href="{% url 'trans:index' %}" class="btn btn-dark">번역기</a>
                        <a href="{% url 'tts:index' %}" class="btn btn-dark">TTS</a>
                    </div>
                {% endblock %}
            {% else %}
                {% block noauth %}
                    <h1 class="text-center"><b>인증이 필요한 페이지 입니다!</b></h1>
                    <div class="text-center mt-5">
                        <a href="{% url 'acc:login' %}" class="btn btn-dark">로그인</a>
                        <a href="{% url 'acc:signup' %}" class="btn btn-dark">회원가입</a>
                    </div>
                {% endblock %}
            {% endif %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>