acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('changepw/', views.changepw, name="changepw"),
    path('delete/', views.delete, name="delete")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>' , views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('tts/', include("tts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User
from django.utils import timezone
# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=200)
    writer= models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField(blank=True)
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 100:
            return f"{self.content[:100]} ..."
        return self.content

class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.b}_{self.replyer}"

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.core.paginator import Paginator
# Create your views here.

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect("board:detail", bpk)

def unlikey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect("board:detail", bpk)

def index(request):
    pg = request.GET.get("page", 1)
    kw = request.GET.get("kw", "")
    cate = request.GET.get("cate","")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            from acc.models import User
            try:
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.none()
    else:
        b = Board.objects.all()

    pag = Paginator(b, 3)
    obj = pag.get_page(pg)

    context = {
        "bset" : obj,
        "kw" : kw,
        "cate" : cate,
    }
    return render(request, "board/index.html", context)


def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == request.user:
        r.delete()
    else:
        pass # 8일차 메세지
    return redirect("board:detail", bpk)


def creply(request, bpk):
    r = request.POST.get("rep")
    b = Board.objects.get(id=bpk)
    Reply(b=b, replyer=request.user, comment=r).save()
    return redirect("board:detail", bpk)


def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if request.user != b.writer:
        pass # 8일차
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s, c
        b.save()
        return redirect("board:detail", bpk)
    context = {
        "b" :b
    }
    return render(request, "board/update.html", context)


def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, writer=request.user, content=c).save()
        return redirect("board:index")
    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        pass # 8일차
    return redirect("board:index")

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all() # b 한테 딸린 댓글 다나와
    context = {
        "b" : b,
        "rset" : r,
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>게시글 작성</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">SUBJECT</label>
            <input type="text" name="sub" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">WRITER</label>
            <input type="text" class="form-control" value="{{ user }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea name="con" class="form-control" style="height: 150px;"></textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>{{ b.subject }}</b></h1>

    <div class="row mt-4">
        <div class="col-sm-9">
            <textarea class="form-control" disabled style="height: 200px;">{{ b.content }}</textarea>
        </div>
        <div class="col-sm-3 text-center">
            <img src="{{ b.writer.getpic }}" width="90%">
            <div class="mt-3">
                <h5>written by <b>{{b.writer}}</b></h5>
            </div>
            <div class="text-end mt-3">
                {{ b.pubdate | date:'Y년 m월 d일 H:i' }}
            </div>
        </div>
    </div>

    <div class="text-end mt-4">
        <!-- Button trigger modal -->
        <a class="btn btn-dark" href="{% url 'board:index' %}">글목록</a>

        {% if user == b.writer %}
            <a class="btn btn-secondary" href="{% url 'board:update' b.id %}">글수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                글삭제 
            </button>
        {% endif %}

    </div>

    <div class="text-end mt-3">
        {% if user in b.likey.all %}
            <a href="{% url 'board:unlikey' b.id %}" class="btn btn-danger btn-sm">👎🏻</a>
        {% else %}
            <a href="{% url 'board:likey' b.id %}" class="btn btn-primary btn-sm">👍🏻</a>
        {% endif %}
    </div>



    <hr>

    <form method="post" action="{% url 'board:creply' b.id %}">
        {% csrf_token %}
        <div class="row mt-3 mb-5">
            <div class="col-sm-10">
                <input type="text" name="rep" class="form-control" placeholder="댓글을 입력하세요..">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-dark" style="width: 100%;">댓글작성</button>
            </div>
        </div>
    </form>

    
    {% if rset %}
        {% for i in rset %}
            <div class="row mt-4">
                <div class="col-sm-3 text-center">
                    <img src="{{ i.replyer.getpic }}" width="100%">
                    <div class="text-center mt-3">
                        <h5><b>{{i.replyer}}</b></h5>
                    </div>
                </div>
                <div class="col-sm-9">
                    <textarea disabled class="form-control" style="height: 130px;">{{ i.comment }}</textarea>
                    <div class="text-end mt-3">
                        {% if user == i.replyer %}
                            <a href="{% url 'board:dreply' b.id i.id %}" class="btn btn-danger">댓글삭제</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h5 class="text-center">첫번째 댓글을 달아주세요🤣</h5>
    {% endif %}





    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}" class="btn btn-danger">삭제</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

    {% load mathfilters %}
    <h1><b>게시판</b></h1>
    
    <div class="text-end">
        <a href="{% url 'board:create' %}" class="btn btn-dark">글쓰기✏</a>
    </div>

    <table class="table mt-4 table-hover">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">WRITER</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% if bset %}
                {% for i in bset %}
                    <tr>
                        <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                        <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                        <td>{{ i.summary }}</td>
                        <td>{{ i.writer }}</td>
                        <td>{{ i.likey.count }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                {% if kw %}
                    <tr>
                        <th colspan="5">검색결과가 없습니다 😉</th>
                    </tr>
                {% else %}
                    <tr>
                        <th colspan="5">첫번째 게시글을 작성해주세요 😂</th>
                    </tr>
                {% endif %}
            {% endif %}
            
        </tbody>
    </table>

    <form>
        <div class="row mt-5">
            <div class="col-sm-2">
                <select name="cate" class="form-select">
                    <option value="sub" {% if cate == 'sub' %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == 'wri' %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == 'con' %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-9">
                <input name="kw" value="{{kw}}" type="text" class="form-control">
            </div>
            <div class="col-sm-1">
                <button class="btn btn-dark" style="width: 100%;">검색</button>
            </div>
        </div>
    </form>



    <nav aria-label="Page navigation example" class="mt-3">
        <ul class="pagination justify-content-center">

            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&kw={{kw}}&cate={{cate}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.previous_page_number}}&kw={{kw}}&cate={{cate}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}

            {% for i in bset.paginator.page_range %}
                {% if bset.number|add:5 >= i and i >= bset.number|sub:4 %}
                    <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&kw={{kw}}&cate={{cate}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.next_page_number}}&kw={{kw}}&cate={{cate}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.paginator.num_pages}}&kw={{kw}}&cate={{cate}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}

        </ul>
    </nav>





    <style>
        .sub {
            text-decoration: none;
            font-weight: bold;
            color : black;
            font-size: 16px;
        }
        .sub:hover {
            color: orange;
        }

    </style>
    
{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>게시글수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">SUBJECT</label>
            <input type="text" name="sub" value="{{ b.subject }}" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">WRITER</label>
            <input type="text" class="form-control" disabled value="{{ b.writer }}">
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">수정</button>
        </div> 
    </form>

{% endblock %}